POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
	"title": "Functional Programming",
	"author": "Ari Joury",
	"url": "https://towardsdatascience.com/why-developers-are-falling-in-love-with-functional-programming-13514df4048e",
	"likes": 18
}